### ISSUE TITLE
check for support for OpenID Connect Federation

### ISSUE THREAD

**Issue by bwegh** [Erlang-Openid/oidcc#183]
https://openid.net/specs/openid-connect-federation-1_0.html

**Comment by daserzw** [comment]
Hi, check out: 
https://github.com/rohe/ojou_course/blob/master/presentation/OIDC%20Fed%20in%20pictures.pdf
bye,
Davide

**Comment by maennchen** [comment]
Not planned right now. Please comment if this is something you require.
