### ISSUE TITLE
Project Maintenance Status

### ISSUE THREAD

**Issue by maennchen** [Erlang-Openid/oidcc#208]
PRs seem not to be reviewed and no reaction to comments.

Therefore: Is this project still maintained?

If not: Would it be possible to transfer the project as well as all of the package manager permissions to a new maintainer?

If that would be an option, I would move this project into its own organisation and offer myself as the first maintainer.

**Comment by marcvs** [comment]
Sorry for not responding quicker here.

Trouble is in fact that our (only) erlang developer left the institute.
All I could do is run tests and then accept PRs, but I don't think I'm capable of reviewing the code.

We have the access rights to transfer the repo to a different organisation, if you like to take this over.

**Comment by maennchen** [comment]
@marcvs Thanks for your answer.

I've written a message in the elixir forum to see if people are interested in co-maintaining the lib. https://elixirforum.com/t/oidcc-project-maintainer/37260

I'd wait for a week or so to see if there's any interest. Depending on the outcome of that post, we can decide what actions makes sense.

For sure I don't want it to get abandoned, so my support on the matter is clear.

**Comment by maennchen** [comment]
@marcvs I'm going to go ahead and open a new organisation for the project. Since I'm a little short on time right now, I'll start preparing in around a week.

I'll post some details as soon as I'm ready so you can review it.

**Comment by marcvs** [comment]
Cool. In addition, we have a person that will take a look at the code.

**Comment by maennchen** [comment]
@marcvs Sorry again for taking that long.

The reason is that I was looking for someone to help with reviewing the code since I myself am not well acquainted with the erlang tooling since I mostly work with Elixir instead.

I think that it might be good to move forward anyways since it will benefit the project to not let it lay around any longer.

I have set up the organization https://github.com/Erlang-Openid

My short-term plan would be to do all updates necessary for all projects and to begin implementing `JSON Web Token (JWT) Profile`.

Long term I'd like to make sure that the library at least stays updated / fix occurring bugs.

I would propose the following steps:

* Tell me wich people you would like to have in the new organization.
* Transfer the repo to said organization
  - `erljwt`
  - `oidcc`
  - `oidcc_cowboy`
  - `oidcc_psycho`
* Clone them back and modify README to point at the new location

**Comment by marcvs** [comment]
@maennchen Many thanks for taking it up!

Let's move to the Erlang-Openid github organisation. I think these people should be members:
- @bwegh (The original author of oidcc)
- @lburgey (The current maintainer in our team)
- @urost (Another maintainer in our team)
- @BorjaEst (An Erlang enthusiast in our team)
- @marcvs (me)

**Comment by marcvs** [comment]
I'm waiting to become admin for the other three repos...

**Comment by marcvs** [comment]
The original owner at hex is not sure if we can add / transfer ownership in the free version used. 
We're working on this.

**Comment by maennchen** [comment]
@marcvs Adding an owner should be rather easy:

Using `mix`: `mix hex.owner add [oidcc|erljwt] maennchen`
Using `rebar3`: `rebar3 hex owner add [oidcc|erljwt] jonatan@maennchen.ch` (Never tried this myself with rebar)

**Comment by maennchen** [comment]
@marcvs Did you find a way about the permissions? I'd like to release a stable version that runs on OTP 24 :)

**Comment by marcvs** [comment]
We have contacted the original developer via several ways, forwarding your ownerchange requests. But there was no response yet.
We will keep on trying.

**Comment by marcvs** [comment]
Should be done now.

**Comment by bwegh** [comment]
I will also add you to oidcc_psycho and oidcc_cowboy, which I missed to add you to @maennchen

**Comment by bwegh** [comment]
added you also as owner for oidcc_cowboy. oidcc_psycho is not on hex as psycho itself is not on hex.pm

**Comment by maennchen** [comment]
Thanks a lot @bwegh
